// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graphql

type Investor struct {
	InvestorID string   `json:"investorID"`
	Name       string   `json:"name"`
	Orders     []*Order `json:"orders"`
}

type MutationInvestor struct {
	CreateInvestor *Investor `json:"createInvestor"`
}

type Order struct {
	OrderID string  `json:"orderID"`
	Amount  float64 `json:"amount"`
}

type Query struct {
}

type QueryInvestor struct {
	Investors []*Investor `json:"investors"`
}

type CreateInvestorInput struct {
	Name string `json:"name"`
}
