// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graphql

type Investor struct {
	InvestorID string   `json:"investorID"`
	Name       string   `json:"name"`
	Orders     []*Order `json:"orders"`
}

type Mutation struct {
}

type Order struct {
	OrderID    string  `json:"orderID"`
	InvestorID string  `json:"investorID"`
	Amount     float64 `json:"amount"`
}

type Query struct {
}

type CreateInvestorInput struct {
	Name string `json:"name"`
}

type CreateOrderInput struct {
	InvestorID string  `json:"investorID"`
	Amount     float64 `json:"amount"`
}
