// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Account struct {
	ID          string  `json:"id"`
	Email       string  `json:"email"`
	Name        string  `json:"name"`
	Picture     string  `json:"picture"`
	Balance     float64 `json:"balance"`
	LastLoginAt string  `json:"lastLoginAt"`
	CreatedAt   string  `json:"createdAt"`
}

type Mutation struct {
}

type Query struct {
}

type Transaction struct {
	ID            string   `json:"ID"`
	Type          string   `json:"Type"`
	Amount        float64  `json:"Amount"`
	Account       *Account `json:"Account"`
	TargetAccount *Account `json:"TargetAccount"`
	CreatedAt     string   `json:"CreatedAt"`
}

type TransactionResult struct {
	Success     bool         `json:"Success"`
	Message     string       `json:"Message"`
	Transaction *Transaction `json:"Transaction,omitempty"`
}
