// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Investor struct {
	InvestorID   string `json:"investorID"`
	LoginAccount string `json:"loginAccount"`
	Password     string `json:"password"`
}

type Mutation struct {
}

type Query struct {
}

type CreateInvestorInput struct {
	LoginAccount string `json:"loginAccount"`
	Password     string `json:"password"`
}

type QueryInvestorsParams struct {
	InvestorIDs   []string `json:"investorIDs"`
	LoginAccounts []string `json:"loginAccounts"`
	PageSize      int      `json:"pageSize"`
	Page          int      `json:"page"`
}
