// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CreateInvestorInput struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type Investor struct {
	ID       string `json:"id"`
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginInput struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type Mutation struct {
}

type Query struct {
}

type QueryInvestorsInput struct {
	Ids       []string `json:"ids"`
	Usernames []string `json:"usernames"`
	PageSize  int      `json:"pageSize"`
	Page      int      `json:"page"`
}
