package graphql

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.45

import (
	graphql1 "apiserver/graphql"
	"apiserver/graphql/model"
	"context"
	"fmt"
)

// Deposit is the resolver for the Deposit field.
func (r *mutationResolver) Deposit(ctx context.Context, amount float64) (*model.TransactionResult, error) {
	panic(fmt.Errorf("not implemented: Deposit - Deposit"))
}

// Withdraw is the resolver for the Withdraw field.
func (r *mutationResolver) Withdraw(ctx context.Context, amount float64) (*model.TransactionResult, error) {
	panic(fmt.Errorf("not implemented: Withdraw - Withdraw"))
}

// Transfer is the resolver for the Transfer field.
func (r *mutationResolver) Transfer(ctx context.Context, toAccountID string, amount float64) (*model.TransactionResult, error) {
	panic(fmt.Errorf("not implemented: Transfer - Transfer"))
}

// Mutation returns graphql1.MutationResolver implementation.
func (r *Resolver) Mutation() graphql1.MutationResolver { return &mutationResolver{r} }

type mutationResolver struct{ *Resolver }
